export interface RatingInput {
  /** Percentage of the track performed on live instruments (0-100). */
  liveInstrumentsPct: number;
  /** Vocals were recorded by a human performer. */
  liveVocals: boolean;
  /** Lyrics were written by a human. */
  handwrittenLyrics: boolean;
  /** AI tools were used somewhere in production (mixing, mastering, etc.). */
  aiAssistedProduction: boolean;
  /** The melody was generated by an AI model. */
  aiGeneratedMelody: boolean;
  /** The lyrics were generated by an AI model. */
  aiGeneratedLyrics: boolean;
}

export interface Song {
  id: string;
  title: string;
  artist: string;
  description: string;
  /** Price in USD cents. */
  priceCents: number;
  rating: RatingInput;
  /** Computed 0-100 "how human-made" score. */
  humanMadeScore: number;
  humanMadeLabel: string;
  createdAt: string;
  sales: number;
}

export type NewSongInput = Omit<
  Song,
  "id" | "humanMadeScore" | "humanMadeLabel" | "createdAt" | "sales"
>;
