"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { computeHumanMadeScore, ratingLabel } from "@/lib/rating";
import HumanMadeBadge from "@/components/HumanMadeBadge";
import type { RatingInput } from "@/lib/types";

const CHECKBOXES: { key: keyof RatingInput; label: string }[] = [
  { key: "liveVocals", label: "Vocals recorded by a human" },
  { key: "handwrittenLyrics", label: "Lyrics written by a human" },
  { key: "aiAssistedProduction", label: "AI used in production/mastering" },
  { key: "aiGeneratedMelody", label: "Melody generated by AI" },
  { key: "aiGeneratedLyrics", label: "Lyrics generated by AI" },
];

export default function UploadPage() {
  const router = useRouter();
  const [title, setTitle] = useState("");
  const [artist, setArtist] = useState("");
  const [description, setDescription] = useState("");
  const [price, setPrice] = useState("0.99");
  const [rating, setRating] = useState<RatingInput>({
    liveInstrumentsPct: 80,
    liveVocals: true,
    handwrittenLyrics: true,
    aiAssistedProduction: false,
    aiGeneratedMelody: false,
    aiGeneratedLyrics: false,
  });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const score = useMemo(() => computeHumanMadeScore(rating), [rating]);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    setError("");
    try {
      const res = await fetch("/api/songs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          artist,
          description,
          priceCents: Math.round(parseFloat(price || "0") * 100),
          ...rating,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Failed to publish");
      router.push(`/songs/${data.song.id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to publish");
      setSubmitting(false);
    }
  }

  return (
    <div className="grid gap-6 md:grid-cols-[1fr_300px]">
      <form onSubmit={submit} className="card p-6">
        <h1 className="mb-6 text-2xl font-black">Sell your music</h1>

        <div className="mb-4">
          <label className="label" htmlFor="title">
            Song title
          </label>
          <input
            id="title"
            className="input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="e.g. Sunrise on Mars"
            required
          />
        </div>

        <div className="mb-4">
          <label className="label" htmlFor="artist">
            Artist name
          </label>
          <input
            id="artist"
            className="input"
            value={artist}
            onChange={(e) => setArtist(e.target.value)}
            placeholder="Your stage name"
            required
          />
        </div>

        <div className="mb-4">
          <label className="label" htmlFor="description">
            Description
          </label>
          <textarea
            id="description"
            className="input min-h-24"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Tell listeners the story behind the track"
            required
          />
        </div>

        <div className="mb-6">
          <label className="label" htmlFor="price">
            Price (USD)
          </label>
          <input
            id="price"
            className="input"
            type="number"
            min="0"
            step="0.01"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
            required
          />
        </div>

        <div className="mb-4">
          <label className="label" htmlFor="live">
            Live instruments: {rating.liveInstrumentsPct}%
          </label>
          <input
            id="live"
            type="range"
            min="0"
            max="100"
            value={rating.liveInstrumentsPct}
            onChange={(e) =>
              setRating((r) => ({
                ...r,
                liveInstrumentsPct: Number(e.target.value),
              }))
            }
            className="w-full accent-boss-accent"
          />
        </div>

        <div className="mb-6 space-y-2">
          {CHECKBOXES.map((c) => (
            <label
              key={c.key}
              className="flex cursor-pointer items-center gap-3 rounded-lg border border-white/10 bg-black/20 px-3 py-2"
            >
              <input
                type="checkbox"
                className="h-4 w-4 accent-boss-accent"
                checked={Boolean(rating[c.key])}
                onChange={(e) =>
                  setRating((r) => ({ ...r, [c.key]: e.target.checked }))
                }
              />
              <span className="text-sm">{c.label}</span>
            </label>
          ))}
        </div>

        {error && (
          <p className="mb-4 rounded-lg border border-rose-400/40 bg-rose-400/10 px-3 py-2 text-sm text-rose-200">
            {error}
          </p>
        )}

        <button
          type="submit"
          disabled={submitting}
          className="btn-primary w-full disabled:opacity-60"
        >
          {submitting ? "Publishing…" : "Publish to marketplace"}
        </button>
      </form>

      <aside className="card h-fit p-6 text-center">
        <p className="mb-3 text-sm text-white/60">Live human-made rating</p>
        <div className="mb-4 text-6xl font-black">{score}</div>
        <HumanMadeBadge score={score} label={ratingLabel(score)} size="md" />
        <p className="mt-4 text-xs text-white/40">
          Updates as you describe how the track was made.
        </p>
      </aside>
    </div>
  );
}
